config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  resources :orders  
  resources :executors
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services, dependent: :destroy

  validates :title, presence: true
end

app/models/executor.rb
class Executor < ApplicationRecord
  has_many :services, dependent: :destroy

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :services, dependent: :destroy

  accepts_nested_attributes_for :services, reject_if: :all_blank, allow_destroy: true

  validates :customer_name, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
  belongs_to :executor
  belongs_to :order
  
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/executors_controller.rb
class ExecutorsController < ApplicationController
  before_action :set_executor, only: %i[show edit update destroy]

  def index
    @executors = Executor.all
  end

  def show; end

  def new
    @executor = Executor.new
  end

  def create
    @executor = Executor.new(executor_params)

    if @executor.save
      redirect_to @executor
    else
      render :new
    end
  end

  def edit; end

  def update
    if @executor.update(executor_params)
      redirect_to @executor
    else
      render :edit
    end
  end

  def destroy
    @executor.destroy

    redirect_to executors_path
  end

  private

  def set_executor
    @executor = Executor.find(params[:id])
  end

  def executor_params
    params.require(:executor).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = Order.all
  end

  def show; end

  def new
    @order = Order.new
    @order.services.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order
    else
      render :new
    end
  end
  
  def edit; end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      render :edit
    end
  end

  def destroy
    @order.destroy

    redirect_to orders_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:customer_name, :caterory_id, :executor_id, services_attributes: [:id, :title, :category_id, :executor_id, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/executors_helper.rb
module ExecutorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/categories/_category.html.slim
tr
  td= category.title
  td=> link_to 'Show', category_path(category)
  td=< link_to 'Delete', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' }
              

app/views/categories/_form.html.slim
= form_with model: @category, local: true do |f|
  = render 'shared/errors', resource: @category

  div
    = f.label :title
    = f.text_field :title, id: :category_title
  div
    = f.submit
    

app/views/categories/edit.html.slim
h1= "Category: #{@category.title}" 

= render 'form'
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 All Categories
p= link_to 'New category', new_category_path

table
  tr
    th Category
    th colspan=2 Actions

  = render @categories
  

app/views/categories/new.html.slim
h1 Create new category

= render 'form'
= link_to 'Back', categories_path

app/views/categories/show.html.slim
h1= "Category: #{@category.title}"

div
  strong Category: 
  =@category.title
dev 
  => link_to 'Edit', edit_category_path(@category)
  '|
  =< link_to  'Back', categories_path
  

app/views/executors/_executor.html.slim
tr
  td= executor.name
  td=> link_to 'Show', executor_path(executor)
  td=< link_to 'Delete', executor_path(executor),
              method: :delete,
              data: { confirm: 'Are you sure?' }
              

app/views/executors/_form.html.slim
= form_with model: @executor, local: true do |f|
  = render 'shared/errors', resource: @executor

  div
    = f.label :name
    = f.text_field :name, id: :executor_name
  div
    = f.submit
    

app/views/executors/edit.html.slim
h1= "Execute name: #{@executor.name}" 

= render 'form'
= link_to 'Back', executors_path

app/views/executors/index.html.slim
h1 All Executes
p= link_to 'New executor', new_executor_path

table
  tr
    th Executor name
    th colspan=2 Actions

  = render @executors
  

app/views/executors/new.html.slim
h1 Create new executor

= render 'form'
= link_to 'Back', executors_path

app/views/executors/show.html.slim
h1= "Executor name: #{@executor.name}"

div
  strong Executor name: 
  =@executor.name
dev 
  => link_to 'Edit', edit_executor_path(@executor)
  '|
  =< link_to  'Back', executors_path
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.slim
= render 'shared/errors', resource: @order

= form_with model: @order, local: true do |form|
  => form.label :customer_name
  = form.text_field :customer_name, id: :order_customer_name
  
  h3 Services:
  = link_to_add_nested(form, :services, '#services', link_text: 'Add service')
  div id='services'
    = form.fields_for :services do |service_f|
      = render 'service_fields', form: service_f
    
  = form.submit

app/views/orders/_order.html.slim
tr
  td= order.id
  td= order.customer_name
  td= order.created_at.to_date
  td=> link_to 'Show', order_path(order)
  td=< link_to 'Delete', order_path(order),
              method: :delete,
              data: { confirm: 'Are you sure?' }
              

app/views/orders/_service_fields.html.slim
div
  => form.label :title
  => form.text_field :title
  => form.label :cateroy_id
  => form.collection_select :category_id, Category.all, :id, :title, promt: true
  => form.label :executor_id
  => form.collection_select :executor_id, Executor.all, :id, :name, prompt: true
  = link_to_remove_nested(form, link_text: 'Delete')

app/views/orders/edit.html.slim
h1= "Order number: #{@order.id}" 

= render 'form'
= link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 All Orders
p= link_to 'New order', new_order_path

table
  tr
    th Order number
    th Customer name
    th Date of creation
    th colspan=2 Actions

  = render @orders

app/views/orders/new.html.slim
h1 Create new order

= render 'form'
= link_to 'Back', orders_path

app/views/orders/show.html.slim
div
  strong Customer name: 
  =@order.customer_name
div
  strong Date of creation: 
  =@order.created_at.to_date
div
  strong Servises: 
  -@order.services.each do |s|
    div
      => s.title
      '-
      = s.executor.name
      
dev 
  => link_to 'Edit', edit_order_path(@order)
  '|
  = link_to  'Back', orders_path
  

app/views/shared/_errors.html.slim
- if resource.errors.present?
  div
    h2= "#{pluralize(resource.errors.count, 'error')} detected: "

    ul
      -resource.errors.full_messages.each do |message|
        li= message
        

app/views/shared/_nav.html.slim
nav.navbar.navbar-light.bg-light.shadow
  .container
    => link_to 'Orders', orders_path, class: 'navbar-brand'
    '|
    =< link_to 'Executors', executors_path, class: 'navbar-brand'
    '|
    => link_to 'Categories', categories_path, class: 'navbar-brand'